# Generated by Django 5.0.3 on 2024-04-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
